(() => {
    const entries = {
        'Preview card payment': 'معاينة الدفع بالبطاقة',
        'Preview the card payment page while activation is pending. No payment or order will be submitted.': 'يمكنك معاينة صفحة البطاقة لحين التفعيل. لن يتم إرسال طلب أو إجراء دفع.',
        'After Place Order, enter your card details on the secure payment page. No account needed.': 'بعد تأكيد الطلب، أدخل بيانات بطاقتك في صفحة الدفع الآمن. لا تحتاج إلى حساب.',
        'Already have an account?': 'لديك حساب بالفعل؟',
        'Home':'الرئيسية', 'Shop':'المتجر', 'Brands':'العلامات التجارية', 'New Arrivals':'وصل حديثًا', 'Offers':'العروض', 'About':'عن المتجر', 'About Us':'عن المتجر', 'Contact Us':'تواصل معنا',
        'NEW ARRIVALS ✦ EXCLUSIVE DEALS ✦ LIMITED PIECES ✦ SHOP NOW ✦ BONDOK STORE ✦':'وصل حديثًا ✦ عروض حصرية ✦ قطع محدودة ✦ تسوق الآن ✦ بندق ستور ✦',
        'Search products':'ابحث عن المنتجات', 'Search':'بحث', 'Logout':'تسجيل الخروج', 'Admin Panel':'لوحة الإدارة',
        'Bondok Store since 2020':'بندق ستور منذ ٢٠٢٠', 'Our promise':'وعدنا', 'Good clothes, clear service.':'ملابس مميزة وخدمة واضحة.',
        'From the first click to delivery at your door, Bondok keeps shopping direct, considered, and easy.':'من أول ضغطة لحد وصول طلبك لباب البيت، بندق بيخلي تجربة التسوق سهلة وواضحة.',
        'Fast Delivery':'توصيل سريع', 'All over Egypt':'لكل أنحاء مصر', 'Cash on Delivery':'الدفع عند الاستلام', 'Pay when you receive':'ادفع عند الاستلام', '2-Day Exchanges':'استبدال خلال يومين', 'Exchange within 2 days':'استبدال خلال يومين', '100% Original':'أصلي ١٠٠٪', 'Selected for you':'مختار ليك',
        'Get directions':'الاتجاهات', 'Quick Links':'روابط سريعة', 'Customer Service':'خدمة العملاء', 'Orders & Shipping':'الطلبات والشحن', 'Exchanges':'الاستبدال', 'Policies':'السياسات', 'FAQs':'الأسئلة الشائعة', 'Get In Touch':'تواصل معنا', 'Contact us: 01275446186':'اتصل بنا: 01275446186', '© 2026 Bondok Store. All rights reserved.':'© 2026 بندق ستور. جميع الحقوق محفوظة.', '2:00 AM - 2:00 PM':'٢ صباحًا - ٢ ظهرًا',
        'Our edit':'اختياراتنا', 'Brands worth knowing.':'علامات تجارية تستحق التجربة.', 'A considered mix of familiar names and everyday favorites.':'تشكيلة مختارة من علاماتك المفضلة وقطع تناسب كل يوم.',
        'Checkout':'إتمام الطلب', 'One step closer':'باقي خطوة واحدة', 'Complete your order.':'كمّل طلبك.', 'Your bag is empty.':'سلة التسوق فاضية.', 'Find something you love to get started.':'اختار القطع اللي بتحبها وابدأ التسوق.', 'Explore the collection':'شوف التشكيلة', 'Your information':'بياناتك', 'Enter your details to complete the order. No account needed.':'اكتب بياناتك لإتمام الطلب، مش محتاج تعمل حساب.',
        'Full name':'الاسم بالكامل', 'Email address':'البريد الإلكتروني', 'Phone number':'رقم الموبايل', 'Shipping address':'عنوان الشحن', 'Where should we deliver your order?':'تحب نوصّل طلبك فين؟', 'Full address':'العنوان بالكامل', 'Governorate':'المحافظة', 'Loading governorates...':'جاري تحميل المحافظات...', 'Payment method':'طريقة الدفع',
        'Confirm your order with online payment. Delivery within 48 working hours after confirmation.':'أكد طلبك بالدفع أونلاين. التوصيل خلال ٤٨ ساعة عمل بعد التأكيد.', 'Visa / Mastercard':'فيزا / ماستركارد', 'Pay securely online with your credit or debit card.':'ادفع أونلاين بأمان باستخدام بطاقتك البنكية.', 'Card payments are awaiting activation. Please choose another payment method for now.':'الدفع بالبطاقة في انتظار التفعيل. اختار طريقة دفع تانية حاليًا.',
        'Cash on delivery with deposit only':'الدفع عند الاستلام بعربون', 'Pay shipping + 50 EGP deposit now, then the remaining product balance on delivery.':'ادفع الشحن + ٥٠ جنيه عربون دلوقتي، وباقي قيمة المنتجات عند الاستلام.', 'Send':'حوّل', 'to 01275446186':'إلى 01275446186', 'Choose the service you used, then upload your receipt.':'اختار الخدمة اللي استخدمتها وارفع إيصال التحويل.', 'Payment service':'خدمة الدفع', 'InstaPay':'إنستاباي', 'Vodafone Cash':'فودافون كاش', 'Upload payment receipt':'ارفع إيصال الدفع', 'JPG, PNG or WebP, under 10 MB.':'صورة JPG أو PNG أو WebP بحجم أقل من ١٠ ميجابايت.', 'Your order is confirmed after your payment is reviewed.':'هنأكد طلبك بعد مراجعة الدفع.',
        'Order summary':'ملخص الطلب', 'Product subtotal':'إجمالي المنتجات', 'Shipping':'الشحن', 'Select governorate':'اختار المحافظة', 'Deposit (included in subtotal)':'العربون (جزء من قيمة المنتجات)', 'Total':'الإجمالي', 'Pay now':'المطلوب دفعه الآن', 'Remaining on delivery':'المتبقي عند الاستلام', 'Size and color are fixed for checkout. To change them, return to the product and start a new order.':'المقاس واللون ثابتين أثناء إتمام الطلب. لتغييرهم ارجع للمنتج وابدأ طلب جديد.', 'Place Order':'تأكيد الطلب', 'Exchanges within 2 days only. No returns or refunds.':'الاستبدال خلال يومين فقط. لا يوجد إرجاع أو استرداد للمبلغ.', 'Read our policy.':'اقرأ سياستنا.',
        'Skip to content':'انتقل للمحتوى', 'Bondok / Customer care':'بندق / خدمة العملاء', 'A few answers, before you ask.':'إجابات لأسئلتك.', 'Everyday questions about shopping with Bondok.':'أسئلة شائعة عن التسوق مع بندق.', 'On this page':'في الصفحة دي', 'Shopping & payment':'التسوق والدفع', 'Delivery & orders':'التوصيل والطلبات', 'Exchanges & support':'الاستبدال والدعم', 'Made for your everyday.':'اختيارات تناسب كل يوم.', 'Here to help with the details.':'معاك في كل التفاصيل.',
        'How do I place an order?':'إزاي أعمل طلب؟', 'Choose your products in the shop, add them to your bag, and complete the delivery and payment details at checkout.':'اختار منتجاتك من المتجر، ضيفها للسلة، وكمّل بيانات التوصيل والدفع عند إتمام الطلب.', 'How can I pay?':'إزاي أقدر أدفع؟', 'Pay online with Visa or Mastercard through Paymob when available. Cash on delivery is also available: pay shipping plus a 50 EGP deposit to 01275446186 and upload the receipt. The deposit is deducted from the product price.':'تقدر تدفع بفيزا أو ماستركارد من خلال Paymob عند توفرها، أو تدفع عند الاستلام: حوّل الشحن و٥٠ جنيه عربون إلى 01275446186 وارفع الإيصال. العربون بيتخصم من سعر المنتجات.',
        'Where can I browse brands and offers?':'فين ألاقي العلامات التجارية والعروض؟', 'Open Brands or Offers in the main menu to explore the current selection.':'افتح العلامات التجارية أو العروض من القائمة الرئيسية وشوف التشكيلة المتاحة.', 'Where do you deliver?':'بتوصلوا فين؟', 'We deliver across Egypt. Message us to confirm service and estimated timing for your address.':'بنوصل لكل أنحاء مصر. ابعتلنا لتأكيد توفر التوصيل والموعد المتوقع لعنوانك.', 'How much does shipping cost?':'الشحن بكام؟', 'Shipping depends on your governorate and is added to your subtotal at checkout. Read Orders & Shipping for the full delivery fee table.':'تكلفة الشحن حسب المحافظة وبتتضاف للإجمالي عند إتمام الطلب. شوف جدول الأسعار في صفحة الطلبات والشحن.',
        'How do I check my order?':'إزاي أتابع طلبي؟', 'Send your order number and checkout phone number to our WhatsApp team for an update.':'ابعت رقم الطلب ورقم الموبايل المستخدم في الطلب لفريقنا على واتساب.', 'Can I change or cancel my order?':'ينفع أعدّل أو ألغي طلبي؟', 'Contact us as soon as possible. We will check the status and available options before dispatch.':'تواصل معانا في أسرع وقت، وهنراجع حالة الطلب والخيارات المتاحة قبل الشحن.', 'What is your exchange policy?':'إيه سياسة الاستبدال؟', 'We offer exchanges within 2 days of delivery only. We do not accept returns or offer refunds. Read our Exchanges page for conditions and instructions.':'الاستبدال متاح خلال يومين من الاستلام فقط. لا يوجد إرجاع أو استرداد للمبلغ. شوف الشروط والخطوات في صفحة الاستبدال.',
        'Can I exchange a size or colour?':'ينفع أغيّر المقاس أو اللون؟', 'Yes, within 2 days of delivery, subject to item condition and replacement availability. Contact us to arrange the exchange.':'أيوه، خلال يومين من الاستلام حسب حالة المنتج وتوفر البديل. تواصل معانا لترتيب الاستبدال.', 'How do I contact Bondok?':'إزاي أتواصل مع بندق؟', 'Use the WhatsApp or email button below. Include your order number if your question concerns a purchase.':'استخدم زر واتساب أو الإيميل تحت، وضيف رقم الطلب لو سؤالك عن عملية شراء.', "Let's talk":'خلينا نتكلم', 'Still need a hand?':'لسه محتاج مساعدة؟', 'Our team can help you with your next step.':'فريقنا موجود يساعدك في الخطوة الجاية.', 'Chat on WhatsApp':'كلّمنا على واتساب', 'Email us':'راسلنا بالإيميل',
        'Your everyday essentials':'أساسياتك لكل يوم', 'Find your next favorite.':'اكتشف قطعتك المفضلة.', 'Shop now':'تسوق الآن', 'Shop Now':'تسوق الآن', 'Shop your favorite brands':'تسوق علاماتك المفضلة', 'Find your style':'اكتشف ستايلك', 'Shop by category':'تسوق حسب القسم', 'Knitwear':'تريكو', 'Hoodie':'هودي', 'Pants':'بناطيل', 'Jackets':'جاكيتات', 'Accessories':'إكسسوارات', 'Our most wanted':'الأكثر طلبًا', 'Best Sellers':'الأكثر مبيعًا', 'View all products':'شوف كل المنتجات',
        'Your cart':'سلة التسوق', 'Subtotal':'الإجمالي الفرعي', 'Saved for later':'محفوظ لوقت لاحق', 'Your wishlist':'المفضلة', 'My profile':'حسابي', 'Your details':'بياناتك', 'Name':'الاسم', 'Email':'البريد الإلكتروني', 'Phone':'الموبايل', 'Address':'العنوان', 'Save profile':'حفظ البيانات',
        'Back to store →':'الرجوع للمتجر ←', 'Bondok — Your Go-To':'بندق — وجهتك المفضلة', 'Shopping Destination':'للتسوق', 'Discover everyday essentials and standout pieces from your favorite brands, all in one place.':'اكتشف أساسياتك اليومية وقطع مميزة من علاماتك المفضلة، كلها في مكان واحد.', 'Find your next favorite. Explore exclusive styles and make every look your own.':'اكتشف قطعتك المفضلة وستايلات حصرية تكمّل إطلالتك.', 'Login':'تسجيل الدخول', 'Password':'كلمة المرور', 'Forgot Password?':'نسيت كلمة المرور؟', "Don't have an account?":'معندكش حساب؟', 'Register':'إنشاء حساب',
        'Browse the collection and see current prices on each product.':'تصفح التشكيلة وشوف الأسعار الحالية لكل منتج.', 'Shop the collection':'تسوق التشكيلة', 'Easy shopping':'تسوق بسهولة', 'Good style should feel simple.':'الأناقة ببساطة.', 'Pay by card and receive your order within 48 working hours after confirmation.':'ادفع بالبطاقة واستلم طلبك خلال ٤٨ ساعة عمل بعد التأكيد.',
        'From checkout to your doorstep.':'من تأكيد الطلب لحد باب بيتك.', 'A little clarity for every step of your order.':'كل تفاصيل وخطوات طلبك بوضوح.', 'Placing your order':'إتمام طلبك', 'Keeping up with your order':'متابعة طلبك', 'What happens next?':'إيه الخطوة الجاية؟', 'Delivery & shipping fees':'التوصيل ومصاريف الشحن', 'Changes & cancellations':'التعديل والإلغاء', 'Choose your pieces, open your bag, and enter your contact and delivery details at checkout.':'اختار قطعك وافتح السلة واكتب بيانات التواصل والتوصيل عند إتمام الطلب.', 'Choose card payment through Paymob when available, or cash on delivery with shipping plus a 50 EGP deposit paid upfront.':'اختار الدفع بالبطاقة عبر Paymob عند توفرها، أو الدفع عند الاستلام مع دفع الشحن و٥٠ جنيه عربون مقدمًا.', 'Complete card payment on Paymob, or transfer to 01275446186 and upload your receipt for verification.':'كمّل الدفع بالبطاقة على Paymob، أو حوّل إلى 01275446186 وارفع إيصالك للمراجعة.',
        'After payment confirmation, your order arrives within 48 working hours. For cash on delivery, the 50 EGP deposit is deducted from the product price; pay only the remaining product balance on delivery.':'بعد تأكيد الدفع، طلبك بيوصل خلال ٤٨ ساعة عمل. في الدفع عند الاستلام، الـ٥٠ جنيه عربون بتتخصم من سعر المنتجات وبتدفع المتبقي بس عند الاستلام.', 'For an update, message our team on WhatsApp with your order number and the phone number used at checkout.':'لمتابعة الطلب، ابعت لفريقنا على واتساب رقم الطلب ورقم الموبايل المستخدم فيه.', 'Keep your order reference and deposit receipt handy so we can find your purchase quickly.':'احتفظ برقم طلبك وإيصال العربون عشان نقدر نوصل لطلبك بسرعة.',
        '01 / Review':'٠١ / المراجعة', 'Your order and deposit are checked.':'بنراجع طلبك والعربون.', '02 / Preparation':'٠٢ / التجهيز', 'Your confirmed items are packed.':'بنجهّز ونغلّف منتجاتك المؤكدة.', '03 / Delivery':'٠٣ / التوصيل', 'Your parcel heads to your address.':'طلبك في الطريق لعنوانك.', 'Select your governorate at checkout to see the delivery fee added to your order total. These prices apply per order.':'اختار محافظتك عند إتمام الطلب عشان تعرف مصاريف الشحن المضافة للإجمالي. الأسعار دي لكل طلب.', 'Delivery fees in EGP':'مصاريف التوصيل بالجنيه المصري', 'Governorate / area':'المحافظة / المنطقة',
        '6th of October':'٦ أكتوبر', 'Alexandria':'الإسكندرية', 'Aswan':'أسوان', 'Asyut':'أسيوط', 'Beheira':'البحيرة', 'Beni Suef':'بني سويف', 'Cairo':'القاهرة', 'Dakahlia':'الدقهلية', 'Damietta':'دمياط', 'Fayed':'فايد', 'Fayoum':'الفيوم', 'Gharbeya':'الغربية', 'Giza':'الجيزة', 'Helwan':'حلوان', 'Ismailia':'الإسماعيلية', 'Kafr El Sheikh':'كفر الشيخ', 'Luxor':'الأقصر', 'Matrouh':'مطروح', 'Menoufia':'المنوفية', 'Minya':'المنيا', 'New Valley':'الوادي الجديد', 'North Coast':'الساحل الشمالي', 'North Sinai':'شمال سيناء', 'Port Said':'بورسعيد', 'Qalyubia':'القليوبية', 'Qena':'قنا', 'Red Sea':'البحر الأحمر', 'Sharkeya':'الشرقية', 'Sohag':'سوهاج', 'South Sinai':'جنوب سيناء', 'Suez':'السويس',
        'Contact us for an estimated delivery date for your address.':'تواصل معانا لمعرفة موعد التوصيل المتوقع لعنوانك.', 'Contact us promptly if your address, items, or plans change. Include your order number; our team will check whether the parcel can still be changed or cancelled before dispatch.':'لو عايز تغيّر العنوان أو المنتجات أو تلغي الطلب، تواصل معانا بسرعة وابعت رقم طلبك. فريقنا هيراجع إمكانية التعديل أو الإلغاء قبل الشحن.',
        'Good shopping starts with clarity.':'تسوق مريح بتفاصيل واضحة.', 'The essentials of shopping with Bondok Store.':'كل اللي محتاج تعرفه للتسوق مع بندق ستور.', 'Exchanges only':'استبدال فقط', 'Payment':'الدفع', 'Privacy & your information':'الخصوصية وبياناتك', 'Your account & purchases':'حسابك ومشترياتك', 'Support & updates':'الدعم والتحديثات', 'Exchanges are available within 2 days of delivery only. No returns or refunds. Keep items unused with tags, packaging, and proof of purchase. See':'الاستبدال متاح خلال يومين من الاستلام فقط، ولا يوجد إرجاع أو استرداد للمبلغ. احتفظ بالمنتج بدون استخدام ومعاه التاج والتغليف وإثبات الشراء. راجع', 'for exclusions and instructions.':'للاطلاع على الاستثناءات والتعليمات.', 'Delivery is available across Egypt. Timing and charges depend on your address. See':'التوصيل متاح لكل أنحاء مصر. الموعد والتكلفة حسب عنوانك. راجع', 'for details.':'للتفاصيل.',
        'Prices are shown in EGP. Pay online with Visa or Mastercard through Paymob when available. For cash on delivery, shipping and a 50 EGP deposit are paid upfront. The deposit is deducted from the product price, not added to the total. Transfer receipts require verification before confirmation.':'الأسعار بالجنيه المصري. الدفع أونلاين بفيزا أو ماستركارد عبر Paymob عند توفرها. للدفع عند الاستلام، بتدفع الشحن و٥٠ جنيه عربون مقدمًا. العربون بيتخصم من سعر المنتج ومش بيتضاف للإجمالي. إيصالات التحويل بتتراجع قبل التأكيد.', 'Your contact details, address, and payment receipt help us handle purchases and support requests. Delivery requires sharing necessary details with the delivery provider. Contact us about accessing or correcting your information.':'بنستخدم بيانات التواصل والعنوان وإيصال الدفع لتنفيذ طلباتك ومساعدتك. التوصيل بيتطلب مشاركة البيانات اللازمة مع شركة الشحن. تواصل معانا للاطلاع على بياناتك أو تصحيحها.', 'Protect your login details and provide accurate checkout information. Stock may change; contact support if an item becomes unavailable. Website images and branding belong to their respective owners.':'حافظ على بيانات دخولك واكتب بيانات دقيقة عند الطلب. المخزون ممكن يتغير؛ تواصل مع الدعم لو منتج بقى غير متاح. الصور والعلامات التجارية ملك لأصحابها.', 'Contact Bondok through the email or WhatsApp links below for help with an order or these policies. Review this page for changes before your next purchase.':'تواصل مع بندق من روابط الإيميل أو واتساب تحت لو محتاج مساعدة في طلب أو السياسات. راجع الصفحة قبل أي عملية شراء جديدة لمعرفة التحديثات.',
        'Products':'المنتجات', 'Product':'المنتج', 'Loading product...':'جاري تحميل المنتج...', 'Create Account':'إنشاء حساب', 'EG +20 Egypt':'EG +20 مصر', 'Delivery address':'عنوان التوصيل', 'Register Now':'إنشاء الحساب', 'Already have an account?':'عندك حساب بالفعل؟', 'Log in':'تسجيل الدخول',
        'Find your perfect fit.':'اختار المقاس المناسب ليك.', 'Exchanges within 2 days of delivery. No returns or refunds.':'الاستبدال خلال يومين من الاستلام. لا يوجد إرجاع أو استرداد للمبلغ.', 'The exchange window':'مدة الاستبدال', 'Before you exchange':'قبل الاستبدال', 'Request an exchange':'طلب استبدال', 'Exchange availability':'إمكانية الاستبدال', 'Something arrived damaged?':'وصلك منتج تالف؟', 'We offer exchanges only, within 2 days of receiving your order. We do not accept returns or offer refunds.':'بنوفّر الاستبدال فقط خلال يومين من استلام طلبك. لا نقبل الإرجاع أو استرداد المبالغ.', 'Keep your receipt, packaging, and tags until you are happy with your purchase.':'احتفظ بالإيصال والتغليف والتاج لحد ما تتأكد إن المنتج مناسب ليك.', 'Items should be unworn, unwashed, and unaltered.':'لازم المنتج يكون بدون لبس أو غسيل أو تعديل.', 'Include the original packaging, attached tags, and proof of purchase.':'رجّع المنتج بالتغليف الأصلي والتاج وإثبات الشراء.', 'Contact us to confirm that your item and preferred replacement are available for exchange.':'تواصل معانا لتأكيد إمكانية الاستبدال وتوفر البديل المطلوب.', 'Message Bondok on WhatsApp with your order number and the item you want to exchange.':'ابعت لبندق على واتساب رقم طلبك والمنتج اللي عايز تستبدله.', 'Tell us the size, colour, or replacement you would like.':'قولنا المقاس أو اللون أو البديل اللي محتاجه.', 'Wait for collection or drop-off instructions before sending your parcel.':'استنى تعليمات الاستلام أو التسليم قبل ما تبعت المنتج.', 'Pack the item securely with its tags and receipt.':'غلّف المنتج كويس مع التاج والإيصال.', 'Exchanges are subject to item inspection and replacement availability. Our team will confirm the exchange arrangements and any delivery costs before you send the item. Returns and refunds are not available.':'الاستبدال بعد فحص المنتج وحسب توفر البديل. فريقنا هيأكد ترتيبات الاستبدال وأي مصاريف توصيل قبل إرسال المنتج. لا يوجد إرجاع أو استرداد للمبلغ.', 'Contact us within 2 days with your order number and clear photos so we can help arrange a replacement.':'تواصل معانا خلال يومين برقم الطلب وصور واضحة عشان نساعدك في الاستبدال.',
        'The collection':'التشكيلة', 'Shop the pieces you will live in.':'قطع تحب تلبسها كل يوم.', 'Everyday essentials, new arrivals, and considered staples in one place.':'أساسيات يومية وأحدث القطع واختيارات مميزة في مكان واحد.',
        'Reset password':'استعادة كلمة المرور', 'Enter your account email to receive a reset code.':'اكتب إيميل حسابك عشان يوصلك رمز استعادة كلمة المرور.', 'Send code':'إرسال الرمز', 'Back to login':'الرجوع لتسجيل الدخول', 'Verify your email':'تأكيد بريدك الإلكتروني', 'Verification code':'رمز التحقق', 'New password':'كلمة المرور الجديدة', 'Confirm password':'تأكيد كلمة المرور', 'Resend code':'إعادة إرسال الرمز', 'Use another email':'استخدام إيميل تاني', 'Code expires in':'ينتهي الرمز خلال', 'Code expired. Request a new code.':'انتهت صلاحية الرمز. اطلب رمز جديد.', 'Passwords do not match.':'كلمتا المرور غير متطابقتين.', 'If this email is registered, a code has been sent.':'لو الإيميل مسجّل عندنا، هيوصلك رمز التحقق.', 'Password reset successfully. You can log in now.':'تم تغيير كلمة المرور. تقدر تسجّل دخول دلوقتي.', 'Enter a valid email address.':'اكتب بريد إلكتروني صحيح.', 'Email recovery is not configured yet. Please contact the store.':'استرجاع الحساب بالإيميل لسه مش مفعّل. تواصل مع المتجر.', 'Please wait one minute before requesting another code.':'استنى دقيقة قبل طلب رمز جديد.', 'Unable to send the email. Please try again later.':'تعذّر إرسال الإيميل. جرّب تاني بعد شوية.', 'Enter a six-digit code and a password of 8–128 characters.':'اكتب رمز من ٦ أرقام وكلمة مرور من ٨ إلى ١٢٨ حرف.', 'This code is invalid or expired. Request a new code.':'الرمز غير صحيح أو انتهت صلاحيته. اطلب رمز جديد.',
        'Show password':'إظهار كلمة المرور', 'Hide password':'إخفاء كلمة المرور', 'Toggle dark mode':'تبديل الوضع الداكن', 'Play slideshow':'تشغيل الصور', 'Pause slideshow':'إيقاف الصور مؤقتًا', 'Cover 1':'الصورة الأولى', 'Cover 2':'الصورة الثانية', 'Cover 3':'الصورة الثالثة',
        'Add to Cart':'أضف للسلة', 'Buy Now':'اشتري الآن', 'Out of stock':'غير متوفر', 'Size':'المقاس', 'Color':'اللون', 'Quantity':'الكمية', 'Select your size':'اختار مقاسك', 'Select your color':'اختار اللون', 'Product details':'تفاصيل المنتج', 'Delivery & exchanges':'التوصيل والاستبدال', 'Delivery information →':'معلومات التوصيل ←', 'Added to your cart.':'اتضاف للسلة.', 'Product unavailable':'المنتج غير متاح', 'Back to shop':'الرجوع للمتجر', 'Hover to zoom / Click to enlarge':'مرّر للتكبير / اضغط لفتح الصورة', 'An everyday piece from the Bondok collection. Choose your size to make it yours.':'قطعة لكل يوم من تشكيلة بندق. اختار المقاس المناسب ليك.', 'Delivery within 48 working hours after order confirmation. Shipping is calculated for your governorate at checkout. Exchanges within 2 days only. No returns or refunds.':'التوصيل خلال ٤٨ ساعة عمل بعد تأكيد الطلب. الشحن حسب المحافظة عند إتمام الطلب. الاستبدال خلال يومين فقط، ولا يوجد إرجاع أو استرداد للمبلغ.',
        'Remove':'حذف', 'Your cart is empty.':'سلة التسوق فاضية.', 'Explore the collection.':'شوف التشكيلة.', 'Continue shopping':'كمّل التسوق', 'Select your governorate':'اختار محافظتك', 'Pay securely with card':'ادفع بأمان بالبطاقة', 'Card payment awaiting activation':'الدفع بالبطاقة في انتظار التفعيل', 'Place order with deposit':'تأكيد الطلب بعربون', 'Submit online payment':'تأكيد الدفع أونلاين', 'Placing order...':'جاري تأكيد الطلب...', 'Invalid email or password.':'الإيميل أو كلمة المرور غير صحيحة.', 'This email is already registered.':'الإيميل ده مسجّل بالفعل.', 'Unable to continue.':'تعذّر إكمال العملية.', 'All':'الكل', 'All brands':'كل العلامات التجارية', 'All categories':'كل الأقسام', 'Sort by':'ترتيب حسب', 'Featured':'المميز', 'Newest':'الأحدث', 'Price: Low to High':'السعر: من الأقل للأعلى', 'Price: High to Low':'السعر: من الأعلى للأقل', 'No products found.':'مفيش منتجات مطابقة.', 'Loading products...':'جاري تحميل المنتجات...'
    };
    const about = 'في بندق ستور، بنؤمن إن الستايل أكتر من مجرد لبس؛ هو طريقتك للتعبير عن نفسك. بنختار بعناية علامات وقطع بتجمع بين الجودة والراحة والستايل العصري، عشان تلاقي اختيارات تشبهك. هدفنا نخلي التسوق سهل وممتع ومختلف، من اكتشاف القطعة المناسبة لحد ما تبقى جزء من ستايلك اليومي. بندق ستور — وجهتك للعلامات التجارية.';
    for (const apostrophe of ['its', 'it’s']) entries[`At Bondok Store, we believe style is more than what you wear — ${apostrophe} how you express yourself. We carefully select brands and pieces that combine quality, comfort, and modern style, giving you a variety of options to create a look that feels like you. Our goal is to make shopping simple, enjoyable, and different — from discovering the right piece to making it part of your everyday style. Bondok Store — Your Brand Destination.`] = about;
    Object.assign(entries, {
        'All Products':'كل المنتجات', 'Add to cart':'أضف للسلة', 'Your wishlist is empty.':'قائمة المفضلة فاضية.', 'No best sellers yet.':'مفيش منتجات في الأكثر مبيعًا حاليًا.', 'No products available in this category yet.':'مفيش منتجات متاحة في القسم ده حاليًا.', 'Profile saved successfully.':'تم حفظ بياناتك.',
        'the amount shown after selecting your governorate':'المبلغ الظاهر بعد اختيار محافظتك', 'Pay securely with Visa or Mastercard on Paymob. Delivery within 48 working hours after payment confirmation.':'ادفع بأمان بفيزا أو ماستركارد عبر Paymob. التوصيل خلال ٤٨ ساعة عمل بعد تأكيد الدفع.', 'Upload a JPG, PNG, or WebP payment receipt under 10 MB.':'ارفع إيصال الدفع بصورة JPG أو PNG أو WebP أقل من ١٠ ميجابايت.', 'Thank you for shopping with Bondok':'شكرًا لتسوقك مع بندق', 'We will review your payment and contact you to confirm your order. Delivery within 48 working hours after confirmation.':'هنراجع الدفع ونتواصل معاك لتأكيد طلبك. التوصيل خلال ٤٨ ساعة عمل بعد التأكيد.', 'Remaining after payment approval':'المتبقي بعد اعتماد الدفع', 'Payment processing':'جاري معالجة الدفع', 'Contact the store to check your order confirmation.':'تواصل مع المتجر للتأكد من تأكيد طلبك.', 'Payment confirmed':'تم تأكيد الدفع', 'Payment unsuccessful':'لم تنجح عملية الدفع', 'Waiting for payment confirmation':'في انتظار تأكيد الدفع', 'Your order will arrive within 48 working hours.':'طلبك هيوصل خلال ٤٨ ساعة عمل.', 'Your order is only confirmed after Paymob verifies the payment.':'بيتأكد طلبك بعد تحقق Paymob من الدفع.', 'Check payment status':'مراجعة حالة الدفع', 'An item is no longer available. Remove it from your cart before continuing.':'أحد المنتجات لم يعد متاحًا. احذفه من السلة عشان تكمّل.',
        'Store management':'إدارة المتجر', 'Orders & payments':'الطلبات والمدفوعات', 'View storefront':'عرض المتجر', 'Signed in securely':'تم تسجيل الدخول بأمان', 'Refresh orders':'تحديث الطلبات', 'Order desk':'إدارة الطلبات', 'Orders & payment verification':'الطلبات والتحقق من المدفوعات', 'Catalog management':'إدارة المنتجات', 'Catalog':'كتالوج المنتجات', 'Product name':'اسم المنتج', 'Price (EGP)':'السعر بالجنيه', 'Stock':'المخزون', 'Category':'القسم', 'Brand':'العلامة التجارية', 'Select / Other':'اختار / أخرى', 'Show in Best Sellers':'إظهار في الأكثر مبيعًا', 'Only products you select here appear in Best Sellers.':'المنتجات اللي بتختارها هنا بس هتظهر في الأكثر مبيعًا.', 'Available colors':'الألوان المتاحة', 'Separate available colors with commas. Leave empty for products without color options.':'افصل الألوان بفواصل. اترك الحقل فارغًا للمنتجات بدون خيارات ألوان.', 'Available sizes':'المقاسات المتاحة', 'Separate sizes with commas. Stock is the total across all sizes.':'افصل المقاسات بفواصل. المخزون هو الإجمالي لكل المقاسات.', 'Product description':'وصف المنتج', 'Fit, fabric, and product details':'المقاس والخامة وتفاصيل المنتج', 'Product photos':'صور المنتج', 'Upload 1 is the main photo shown in the shop. Add more photos for customers to browse.':'الصورة الأولى هي الرئيسية في المتجر. ضيف صور تانية للعملاء.', 'Add another photo':'إضافة صورة أخرى', 'Add product':'إضافة منتج', 'Save changes':'حفظ التعديلات', 'Add a product above and check Show in Best Sellers, or edit an existing product to include it.':'ضيف منتج وحدد إظهار في الأكثر مبيعًا، أو عدّل منتج موجود لإضافته.', 'T-Shirts':'تيشيرتات', 'Swetpants':'بناطيل', 'One size':'مقاس واحد', 'Edit':'تعديل', 'Delete':'حذف', 'Loading dashboard…':'جاري تحميل لوحة الإدارة…',
        'Main navigation':'القائمة الرئيسية', 'Open menu':'فتح القائمة', 'Shopping cart':'سلة التسوق', 'Close cart':'إغلاق السلة', 'Close':'إغلاق', 'Wishlist':'المفضلة', 'Account':'الحساب', 'Increase quantity':'زيادة الكمية', 'Decrease quantity':'تقليل الكمية', 'Enlarge product photo':'تكبير صورة المنتج', 'Previous photo':'الصورة السابقة', 'Next photo':'الصورة التالية', 'Close photo':'إغلاق الصورة', 'Close photos':'إغلاق الصور', 'Bondok Store location':'موقع بندق ستور', 'Social media':'التواصل الاجتماعي'
    });
    const normalize = value => value.replace(/\s+/g, ' ').trim();
    function translate(text) {
        if (document.documentElement.lang !== 'ar') return text;
        const key = normalize(text);
        if (entries[key]) return text.replace(text.trim(), entries[key]);
        if (key.endsWith(' | Bondok Store')) return (entries[key.split(' | ')[0]] || key.split(' | ')[0]) + ' | بندق ستور';
        if (/^[+\d,.]+ EGP$/.test(key)) return key.replace('EGP', 'ج.م');
        if (/^Qty: /.test(key)) return key.replace('Qty:', 'الكمية:');
        if (/^Order #\d+ received\.$/.test(key)) return key.replace('Order #', 'تم استلام الطلب رقم ').replace(' received.', '.');
        if (key.includes(' — ') && key.endsWith(' EGP')) return key.split(' — ').map(translate).join(' — ');
        if (key.startsWith('Search: ')) return key.replace('Search:', 'نتائج البحث:');
        if (key.endsWith(' products')) return 'منتجات ' + key.slice(0, -9);
        if (/^No products available for .* yet\.$/.test(key)) return 'مفيش منتجات متاحة حاليًا لـ ' + key.slice(26,-5);
        if (/^\d+ available$/.test(key)) return key.replace('available', 'متاح');
        if (/^Size: /.test(key)) return key.replace('Size:', 'المقاس:').replace('/ Color:', '/ اللون:').replace('Please choose', 'اختار');
        return text;
    }
    const originals = new WeakMap();
    function apply() {
        observer.disconnect();
        // Translating a label must never change the value submitted to the server.
        document.querySelectorAll('option:not([value])').forEach(option => option.setAttribute('value', option.textContent));
        const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
        let node;
        while ((node = walker.nextNode())) {
            if (node.parentElement?.closest('script,style,svg,[data-language-toggle],#recovery-email')) continue;
            let saved = originals.get(node);
            if (!saved || node.textContent !== saved.output) saved = { original: node.textContent };
            saved.output = translate(saved.original); if (node.textContent !== saved.output) node.textContent = saved.output;
            originals.set(node, saved);
        }
        document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(element => {
            let saved = originals.get(element) || {};
            for (const attribute of ['placeholder','aria-label','title']) {
                if (!element.hasAttribute(attribute)) continue;
                const current = element.getAttribute(attribute);
                if (!saved[attribute] || current !== saved[attribute].output) saved[attribute] = { original:current };
                saved[attribute].output = translate(saved[attribute].original);
                if (current !== saved[attribute].output) element.setAttribute(attribute, saved[attribute].output);
            }
            originals.set(element, saved);
        });
        observer.observe(document.documentElement, { subtree:true, childList:true, characterData:true, attributes:true, attributeFilter:['placeholder','aria-label','title'] });
    }
    const observer = new MutationObserver(apply);
    window.bondokTranslate = translate; window.bondokApplyLanguage = apply;
    apply();
})();
