const assert = require('node:assert/strict');
const { DatabaseSync } = require('node:sqlite');
const { getProductsWithSales } = require('../catalog');
const fs = require('node:fs');
const vm = require('node:vm');
const db = new DatabaseSync(':memory:');
db.exec(`CREATE TABLE products(id INTEGER, name TEXT, price INTEGER, stock INTEGER, category TEXT, brand TEXT, image TEXT, sizes_json TEXT DEFAULT '[]', colors_json TEXT DEFAULT '[]', description TEXT DEFAULT '', best_seller INTEGER DEFAULT 0);
CREATE TABLE orders(status TEXT, items_json TEXT);`);
const product = db.prepare("INSERT INTO products(id, name, price, stock, category, brand, image) VALUES (?, ?, 100, 5, 'Hoodie', 'ZARA', '')");
for (let id = 1; id <= 12; id++) product.run(id, `Product ${id}`);
const order = db.prepare('INSERT INTO orders VALUES (?, ?)');
order.run('Confirmed', JSON.stringify([{ id: 1, quantity: 2 }, { id: 2, quantity: 4 }]));
order.run('Delivered', JSON.stringify([{ id: 1, quantity: 3 }]));
for (const status of ['Rejected', 'Pending Payment Verification', 'Pending Deposit Verification']) {
    order.run(status, JSON.stringify([{ id: 3, quantity: 100 }]));
}
db.exec("UPDATE products SET best_seller = 1 WHERE id IN (1, 3)");
let products = getProductsWithSales(db).map(p => ({ ...p, bestSeller: p.best_seller === 1 }));
assert.equal(products.find(p => p.id === 1).unitsSold, 5);
assert.equal(products.find(p => p.id === 2).unitsSold, 4);
assert.equal(products.find(p => p.id === 3).unitsSold, 0);
const source = fs.readFileSync(require('node:path').join(__dirname, '../script.js'), 'utf8');
const heading = { textContent: 'Best Sellers', dataset: {} };
const clear = {};
const grid = { innerHTML: '', append(message) { this.message = message.textContent; } };
const context = { products, activeCategory: 'all', activeBrand: '', showBestSellers: true,
    searchQuery: '', showAllProducts: false, currentUser: null, wishlist: [], productGrid: grid, formatPrice: String,
    document: { querySelector: s => s === '#shop h2' ? heading : clear, createElement: () => ({ setAttribute() {} }) } };
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function renderProducts()'), source.indexOf('function renderWishlist()')), context);
const render = () => vm.runInContext('renderProducts()', context);
render();
assert.equal((grid.innerHTML.match(/class="product-card"/g) || []).length, 2);
assert.ok(grid.innerHTML.indexOf('Product 1') < grid.innerHTML.indexOf('Product 3'));
assert.equal(clear.hidden, false);
context.showBestSellers = false;
context.showAllProducts = true;
render();
assert.equal((grid.innerHTML.match(/class="product-card"/g) || []).length, 12);
assert.equal(heading.textContent, 'All Products');
context.activeBrand = 'LACOSTE';
render();
assert.equal(grid.innerHTML, '');
assert.match(grid.message, /LACOSTE/);
context.activeBrand = '';
context.showBestSellers = true;
db.exec('UPDATE products SET best_seller = 0');
context.products = getProductsWithSales(db).map(p => ({ ...p, bestSeller: p.best_seller === 1 }));
render();
assert.equal(grid.innerHTML, '');
assert.match(grid.message, /No best sellers/);
db.exec('UPDATE products SET best_seller = 1');
context.showAllProducts = false;
context.products = getProductsWithSales(db).map(p => ({ ...p, bestSeller: p.best_seller === 1 }));
render();
assert.equal((grid.innerHTML.match(/class="product-card"/g) || []).length, 8);
assert.ok(!grid.innerHTML.includes('Product 12'));
context.showAllProducts = true;
render();
assert.equal((grid.innerHTML.match(/class="product-card"/g) || []).length, 12);
context.activeCategory = 'Pants';
render();
assert.equal(grid.innerHTML, '');
db.close();
console.log('Passed: sales totals, order statuses, manual selection, top 8, empty state, all products, and brand filter.');
