const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    try {
        const page = await browser.newPage();
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        const products = Array.from({ length: 21 }, (_, i) => ({ id: i + 1, name: `Piece ${i + 1}`, price: 500, stock: 10, category: i < 10 ? 'Swetpants' : 'Hoodie', brand: 'Other', image: 'images/pants.jpeg', images: ['images/pants.jpeg'], sizes: ['M'], colors: [], bestSeller: i < 12, unitsSold: 100 }));
        await page.route('**/api/products', route => route.fulfill({ json: products }));
        await page.goto('http://localhost:3101');
        await page.locator('.product-card').first().waitFor();
        assert.equal(await page.locator('.product-card').count(), 8);
        await page.click('[data-clear-category]');
        assert.equal(await page.locator('.product-card').count(), 12);
        assert.equal(await page.locator('#shop h2').innerText(), 'Best Sellers');
        await page.click('[data-category="Swetpants"]');
        await page.waitForURL('**/shop.html?category=Swetpants');
        await page.locator('.product-card').first().waitFor();
        assert.equal(await page.locator('.page-heading h1').innerText(), 'Pants');
        assert.equal(await page.locator('.category-section').isVisible(), false);
        await page.click('[data-clear-category]');
        assert.equal(await page.locator('.product-card').count(), 10);
        assert.equal(await page.locator('#shop h2').innerText(), 'Pants');
        await page.goto('http://localhost:3101/shop.html?category=Hoodie');
        await page.locator('.product-card').first().waitFor();
        await page.click('[data-clear-category]');
        assert.equal(await page.locator('.product-card').count(), 11);
        await page.click('.header-search summary');
        assert.equal(await page.locator('dialog[open]').count(), 0);
        await page.fill('#header-search-input', 'Piece 21');
        await page.locator('.header-search button[type=submit]').click();
        await page.waitForURL('**/shop.html?q=Piece+21');
        await page.locator('.product-card').first().waitFor();
        assert.equal(await page.locator('.product-card').count(), 1);
        assert.match(await page.locator('.product-card').innerText(), /Piece 21/);
        await page.click('[data-account-link]');
        await page.waitForURL('**/login.html');
        products.forEach(product => product.bestSeller = false);
        await page.goto('http://localhost:3101');
        await page.getByText('No best sellers yet.').waitFor();
        assert.equal(await page.locator('.product-card').count(), 0);
        await page.route('**/api/auth/me', route => route.fulfill({ json: { user: { name: 'Test admin', role: 'admin' } } }));
        await page.goto('http://localhost:3101/admin-products.html');
        await page.getByText('Welcome, Test admin').waitFor();
        await page.selectOption('[name=category]', 'Hoodie');
        await page.locator('[data-edit-product="11"]').click();
        await page.check('[name=bestSeller]');
        let saved;
        await page.route('**/api/products/11', route => {
            saved = route.request().postDataJSON();
            products[10] = { ...products[10], ...saved, id: 11 };
            return route.fulfill({ json: products[10] });
        });
        await page.click('#product-submit');
        await page.getByText('Product saved.').waitFor();
        assert.equal(saved.bestSeller, true);
        assert.match(await page.locator('#admin-best-sellers').innerText(), /Piece 11/);
        await page.goto('http://localhost:3101');
        await page.locator('.product-card').first().waitFor();
        assert.equal(await page.locator('.product-card').count(), 1);
        assert.deepEqual(errors, []);
        console.log('Passed: manual Best Sellers, empty state, admin selection, category navigation, scoped All products, inline search results and standalone login.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
