const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
    const browser = await chromium.launch({ headless: true, channel: 'chrome' });
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        const product = { id: 1, name: 'Test tee', price: 500, stock: 5, category: 'T-Shirts', image: 'images/cover.jpeg', images: ['images/cover.jpeg'], sizes: ['S','M'], colors: ['Black','White'] };
        await page.route('**/api/products', route => route.fulfill({ json: [product] }));
        await page.route('**/api/products/1', route => route.fulfill({ json: product }));
        await page.route('**/api/payment-options', route => route.fulfill({ json: { card: true } }));
        await page.goto('http://localhost:3100');
        await page.locator('#categories').scrollIntoViewIfNeeded();
        await page.locator('#categories').screenshot({ path: 'category-review.png' });
        assert.equal(await page.locator('.category-photo-card').count(), 5);
        assert.match(await page.locator('.announcement-track').innerText(), /NEW ARRIVALS/);
        await page.setViewportSize({ width: 390, height: 844 });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
        assert.equal(await page.locator('.nav-actions').evaluate(el => getComputedStyle(el).position), 'fixed');
        const bar = await page.locator('.nav-actions').boundingBox();
        assert.equal(Math.round(bar.y + bar.height), 844);
        await page.locator('.announcement-bar').hover();
        assert.equal(await page.locator('.announcement-track').evaluate(el => getComputedStyle(el).animationPlayState), 'paused');
        await page.mouse.move(200, 200);
        assert.equal(await page.locator('.announcement-track').evaluate(el => getComputedStyle(el).animationPlayState), 'running');
        assert.equal(await page.locator('.offer-banner').count(), 0);
        await page.goto('http://localhost:3100/product.html?id=1');
        await page.locator('#detail-photo').waitFor();
        await page.locator('#detail-photo').hover({ position: { x: 80, y: 90 } });
        assert.notEqual(await page.locator('#detail-photo').evaluate(img => img.style.transformOrigin), '');
        await page.selectOption('#product-size', 'M');
        await page.selectOption('#product-color', 'Black');
        await page.click('button[value="buy"]');
        await page.selectOption('select[name="governorate"]', 'asyut');
        assert.equal(await page.locator('input[value="card"]').isChecked(), true);
        assert.equal(await page.locator('#place-order').isEnabled(), true);
        await page.check('input[value="cash_deposit"]');
        assert.equal(await page.locator('#summary-total').innerText(), '610 EGP');
        assert.equal(await page.locator('#summary-due').innerText(), '160 EGP');
        assert.equal(await page.locator('#summary-remaining').innerText(), '450 EGP');
        assert.equal(await page.locator('[data-checkout-size], #checkout-items select').count(), 0);
        assert.match(await page.locator('#checkout-items').innerText(), /Black/);
        assert.equal(await page.locator('input[value="online_transfer"]').count(), 0);
        await page.check('input[value="card"]');
        await page.fill('input[name="name"]', 'Test Customer');
        await page.fill('input[name="email"]', 'test@example.test');
        await page.fill('input[name="phone"]', '01000000000');
        await page.fill('textarea[name="address"]', 'Test address');
        let submitted;
        await page.route('**/api/orders', route => {
            submitted = route.request().postDataJSON();
            return route.fulfill({ status: 503, json: { error: 'Synthetic payment test' } });
        });
        await page.click('#place-order');
        await page.getByText('Synthetic payment test').waitFor();
        assert.equal(submitted.paymentMethod, 'card');
        assert.equal(submitted.paymentScreenshot, '');
        assert.deepEqual(submitted.items, [{ id: 1, size: 'M', color: 'Black', quantity: 1 }]);
        assert.equal(await page.locator('input[name="name"]').isEnabled(), true);
        await page.screenshot({ path: 'checkout-review.png', fullPage: true });
        assert.deepEqual(errors, []);
        console.log('Passed: desktop/mobile collections, marquee, colors, locked variants, card default, COD totals, fixed mobile toolbar and marquee pause/resume.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
